### ISSUE TITLE
Rust client for Drand

### ISSUE THREAD

**Issue by prataprc** [drand/drand-client#13]
I am working on a drand-client in rust. I am using the go implementation `drand/client` for reference and so far it checks fine. For verification I am using [drand-verify](https://github.com/CosmWasm/drand-verify). Before I put some serious effort in drand-rs I want to make sure that the rust-client aligns with Drand requirements and specification. We can have this as the tracking issue for that.

**code**: https://github.com/prataprc/drand-rs

**Comment by AnomalRoil** [comment]
Sorry for not responding earlier. Most of the drand work is going on in the https://github.com/drand/drand

The team has plans to support a Rust client at some point later this year. Initial work has been done here: https://github.com/CluEleSsUK/drand-client-rs/
