### ISSUE TITLE
comment says public_key from`/info` is Ed25519 instead of BLS12-381

### ISSUE THREAD

**Issue by jakehemmerle** [drand/drand-client#41]
[This line](https://github.com/drand/drand-client/blob/master/lib/index.ts#L118) says the `public_key` from `/info` is Ed25519, while the [drand cryptographic specification](https://drand.love/docs/specification/#setup-phase) and the library dependency says it's the BLS12-381 G1 point. Please let me know if this comment needs updating or if I'm just losing my mind. Thanks!

**Comment by CluEleSsUK** [comment]
It’s indeed BLS12-381 - the code comment is incorrect and I’ll update it shortly!

**Comment by jakehemmerle** [comment]
thanks!

closed with #42
