### ISSUE TITLE
Missing "main": "lib/drand.ts",

### ISSUE THREAD

**Issue by webmaster128** [drand/drand-client#44]
in package.json we have ["main": "lib/drand.ts",](https://github.com/drand/drand-client/blob/v1.0.0-pre.0/package.json#L6) which does not exist.

Also shouldn't this point to a compiled .js file? It seems like the npm package does not contain .js builds at all.

**Comment by CluEleSsUK** [comment]
oops, you're quite correct! I only tested in a ts env... where it worked because the ts files were there >.> will fix this!!

**Comment by CluEleSsUK** [comment]
Have raised a PR to fix it all here: https://github.com/drand/drand-client/pull/45
Hopefully will be merged soon!

**Comment by webmaster128** [comment]
Seems like it is fixed now. Thank you!
