### ISSUE TITLE
deno support for v1.0.0

### ISSUE THREAD

**Issue by CluEleSsUK** [drand/drand-client#46]
Deno was supported in v0.* via storing all the JS on a CDN. This is not currently the case for v1 and should be implemented for parity.

**Comment by webmaster128** [comment]
Deno works for me when importing like this:

```
import {
  HttpCachingChain,
  HttpChainClient,
  watch,
} from "npm:drand-client@1.0.0-pre.5";
```

The explicit version is still needed since 1.0 is still in pre-release.

**Comment by CluEleSsUK** [comment]
Yeehaaa!~ https://deno.com/blog/v1.29
