### ISSUE TITLE
watch returns the same round multiple times

### ISSUE THREAD

**Issue by webmaster128** [drand/drand-client#53]
I have the following deno script:

```typescript
import { HttpCachingChain, HttpChainClient, watch } from "npm:drand-client@1.0.0-pre.5";

const chainHash = "8990e7a9aaed2ffed73dbd7092123d6f289930540d7651336225dc172e51b2ce";
const publicKey =
  "868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31"; // (hex encoded)

const options = {
  disableBeaconVerification: false,
  noCache: false,
  chainVerificationParams: { chainHash, publicKey },
};

if (import.meta.main) {
  const chain = new HttpCachingChain("https://api.drand.sh", options);
  const client = new HttpChainClient(chain, options);

  const abortController = new AbortController();
  for await (const beacon of watch(client, abortController)) {
    console.log(new Date().toUTCString(), "Watch returned a beacon:", beacon);
  }
}
```

and run it with `deno run --allow-read --allow-net main.ts > log.txt`. As you can see in the logs, the same round is returned multiple times. E.g. `round: 2618607` is there 302 times.

[log.txt](https://github.com/drand/drand-client/files/10439362/log.txt)

**Comment by webmaster128** [comment]
I think this is related to the use of latest here: https://github.com/drand/drand-client/blob/9bf4c7401b94eb2e7a24c03eff8dd066ffb10f79/lib/index.ts#L93. Once the publish time of `beacon.round + 1` is reached, the code assumes we get this round in the latest call.

**Comment by CluEleSsUK** [comment]
nice catch! have raised a PR to fix it here: https://github.com/drand/drand-client/pull/54

**Comment by CluEleSsUK** [comment]
Complete!

**Comment by webmaster128** [comment]
Confirming it works in drand-client@1.0.0-pre.6

Thank you!
