### ISSUE TITLE
Update testnet node URLs

### ISSUE THREAD

**Issue by webmaster128** [drand/drand-client#7]
Two of the tree testnet endpoints used for testing this lib (https://github.com/drand/drand-client/blob/42b9dfe/drand.test.js#L10-L14 and https://github.com/drand/drand-client/blob/42b9dfe/optimizing.test.js#L12-L16) are currently unavailable for me:

- http://pl-eu.testnet.drand.sh 🔴 
- http://pl-us.testnet.drand.sh 🟢
- http://pl-sin.testnet.drand.sh 🔴

Are they expected to become available again? Are there alternative nodes that can be used for testing with multiple clients?

**Comment by CluEleSsUK** [comment]
This has been fixed in https://github.com/drand/drand-client/pull/28, although I don't have an answer as to when there will be alternative nodes for testing multiple clients!

**Comment by AnomalRoil** [comment]
Closing, feel free to re-open if it's not enough.
